### ISSUE TITLE
Feat: 현재 위치 기반으로 날씨 데이터 출력 (OpenWeather API)

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/how-weather-wear#5]
##  📌 Overview
- OpenWeather API를 연결합니다.
- 현재 위치를 기반으로 날씨 데이터를 출력합니다.

<br />

## ✔️ Todo
- [x] API 연결
- [x] 응답 데이터 구조체 설정
- [x] 응답 데이터 바인딩
  - [x] 현재 위치
  - [x] 현재 온도
  - [x] 최고 온도
  - [x] 최저 온도
- [ ] ~~지도 움직이는 경우 유스케이스 대응~~ → 별도 브랜치에서 진행

<br />

## 🔗 References
- [[iOS] CLGeocoder 위도,경도 정보로 지역명 가져오기](https://velog.io/@rose6649/iOS-CLGeocoder-위도경도-정보로-지역명-가져오기)
- [[iOS/SwiftUI] MapKit, 실시간으로 도로명 주소 반환하기](https://codekodo.tistory.com/210)
- [mapViewDidChangeVisibleRegion](https://developer.apple.com/documentation/mapkit/mkmapviewdelegate/2998428-mapviewdidchangevisibleregion)
- [regionDidChangeAnimated](https://developer.apple.com/documentation/mapkit/mkmapviewdelegate/1452345-mapview)

<br />
