### ISSUE TITLE
Refactor: 현재 온도 소수점 처리 수정, UI 수정

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/how-weather-wear#7]
##  📌 Overview
- 기능 동작과 연관이 없는 부분들에 대한 수정을 진행합니다.

<br />

## ✔️ Todo
- [x] 최고/최저 온도 폰트 색상 수정
- [x] 현재 온도 소숫점 버림 처리
- [x] 레이아웃, UI 중복 코드 수정
- [x] 불필요한 코드 제거
- [x] 리터럴 데이터 상수화
